"use client"
import { useState, useEffect, useRef } from "react"
import { useRouter } from "next/navigation"
import Link from "next/link"

function slugify(str: string): string {
  return str
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
}

type Step = "choose" | "operator" | "guide"
type SlugStatus = "idle" | "checking" | "available" | "unavailable" | "invalid-format"

export default function OnboardingPage() {
  const router = useRouter()
  const [step, setStep] = useState<Step>("choose")

  // Operator form state
  const [name, setName] = useState("")
  const [slug, setSlug] = useState("")
  const [email, setEmail] = useState("")
  const [cnpj, setCnpj] = useState("")
  const [password, setPassword] = useState("")
  const [slugStatus, setSlugStatus] = useState<SlugStatus>("idle")
  const slugAutoGenerated = useRef(true)

  // Guide lookup state
  const [guideSlug, setGuideSlug] = useState("")
  const [guideSlugChecking, setGuideSlugChecking] = useState(false)
  const [guideSlugError, setGuideSlugError] = useState<string | null>(null)

  const [error, setError] = useState<string | null>(null)
  const [loading, setLoading] = useState(false)

  // Auto-populate slug from operator name
  useEffect(() => {
    if (slugAutoGenerated.current && name) {
      setSlug(slugify(name))
      setSlugStatus("idle")
    }
  }, [name])

  // Debounced operator slug availability check
  useEffect(() => {
    if (step !== "operator") return
    if (!slug) { setSlugStatus("idle"); return }
    if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug)) { setSlugStatus("invalid-format"); return }
    setSlugStatus("checking")
    const timer = setTimeout(async () => {
      try {
        const res = await fetch(`/api/tenants/check-slug?slug=${encodeURIComponent(slug)}`)
        if (res.ok) {
          const data = await res.json()
          setSlugStatus(data.available ? "available" : "unavailable")
        } else {
          setSlugStatus("idle")
        }
      } catch {
        setSlugStatus("idle")
      }
    }, 500)
    return () => clearTimeout(timer)
  }, [slug, step])

  function handleSlugChange(value: string) {
    slugAutoGenerated.current = false
    setSlug(value)
  }

  async function handleOperatorSubmit(e: React.FormEvent) {
    e.preventDefault()
    if (slugStatus === "unavailable" || slugStatus === "invalid-format" || slugStatus === "checking") {
      setError("Corrija o slug antes de enviar.")
      return
    }
    setError(null)
    setLoading(true)
    try {
      const res = await fetch(`/api/tenants/signup`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ name, slug, email, password, cnpj }),
      })
      if (res.ok) {
        router.push("/onboarding/aguardando")
      } else {
        const data = await res.json()
        setError(data.message ?? "Erro ao cadastrar operadora. Tente novamente.")
      }
    } catch {
      setError("Erro de conexão. Verifique sua internet e tente novamente.")
    } finally {
      setLoading(false)
    }
  }

  async function handleGuideSubmit(e: React.FormEvent) {
    e.preventDefault()
    setGuideSlugError(null)
    const normalized = guideSlug.trim().toLowerCase()
    if (!normalized) { setGuideSlugError("Informe o código da operadora."); return }
    setGuideSlugChecking(true)
    try {
      const res = await fetch(`/api/tenants/check-slug?slug=${encodeURIComponent(normalized)}`)
      if (res.ok) {
        const data = await res.json()
        // available: true → slug is FREE (tenant does NOT exist)
        if (data.available) {
          setGuideSlugError("Operadora não encontrada. Verifique o código e tente novamente.")
        } else {
          router.push(`/${normalized}/cadastro`)
        }
      } else {
        setGuideSlugError("Erro ao verificar operadora. Tente novamente.")
      }
    } catch {
      setGuideSlugError("Erro de conexão. Verifique sua internet e tente novamente.")
    } finally {
      setGuideSlugChecking(false)
    }
  }

  const slugIndicator =
    slugStatus === "available" ? (
      <span style={{ color: "#15803D", fontSize: "14px" }} aria-live="polite">✓ Disponível</span>
    ) : slugStatus === "unavailable" ? (
      <span style={{ color: "#DC2626", fontSize: "14px" }} aria-live="polite">✗ Já utilizado</span>
    ) : slugStatus === "checking" ? (
      <span style={{ color: "var(--stone-500)", fontSize: "14px" }} aria-live="polite">Verificando…</span>
    ) : slugStatus === "invalid-format" ? (
      <span style={{ color: "#DC2626", fontSize: "14px" }} aria-live="polite">✗ Formato inválido (use letras, números e hífens)</span>
    ) : null

  // ── Step: choose ──────────────────────────────────────────────────────────
  if (step === "choose") {
    return (
      <main
        style={{
          minHeight: "100dvh",
          background: "var(--stone-50)",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          padding: "24px",
        }}
      >
        <div
          style={{
            background: "white",
            border: "1px solid var(--stone-200)",
            borderRadius: "8px",
            padding: "clamp(32px, 5vw, 48px) clamp(24px, 5vw, 40px)",
            width: "100%",
            maxWidth: "480px",
          }}
        >
          <p
            style={{
              fontSize: "11px",
              fontWeight: 600,
              letterSpacing: "0.06em",
              textTransform: "uppercase",
              color: "var(--ochre)",
              marginBottom: "8px",
            }}
          >
            CAPI
          </p>
          <h1
            style={{
              fontFamily: "var(--font-display)",
              fontSize: "24px",
              fontWeight: 400,
              color: "var(--stone-900)",
              marginBottom: "8px",
            }}
          >
            Criar conta
          </h1>
          <p style={{ fontSize: "14px", color: "var(--stone-500)", marginBottom: "32px" }}>
            Como você quer usar o CAPI?
          </p>

          <div style={{ display: "flex", flexDirection: "column", gap: "12px" }}>
            <button
              onClick={() => setStep("operator")}
              style={{
                width: "100%",
                padding: "20px 20px",
                background: "white",
                border: "1px solid var(--stone-200)",
                borderRadius: "8px",
                cursor: "pointer",
                textAlign: "left",
                transition: "border-color 0.15s",
              }}
              onMouseEnter={(e) => (e.currentTarget.style.borderColor = "var(--ochre)")}
              onMouseLeave={(e) => (e.currentTarget.style.borderColor = "var(--stone-200)")}
            >
              <p style={{ fontSize: "15px", fontWeight: 600, color: "var(--stone-900)", margin: "0 0 4px" }}>
                Sou Operadora
              </p>
              <p style={{ fontSize: "13px", color: "var(--stone-500)", margin: 0 }}>
                Cadastre sua empresa e gerencie guias e roteiros
              </p>
            </button>

            <button
              onClick={() => setStep("guide")}
              style={{
                width: "100%",
                padding: "20px 20px",
                background: "white",
                border: "1px solid var(--stone-200)",
                borderRadius: "8px",
                cursor: "pointer",
                textAlign: "left",
                transition: "border-color 0.15s",
              }}
              onMouseEnter={(e) => (e.currentTarget.style.borderColor = "var(--ochre)")}
              onMouseLeave={(e) => (e.currentTarget.style.borderColor = "var(--stone-200)")}
            >
              <p style={{ fontSize: "15px", fontWeight: 600, color: "var(--stone-900)", margin: "0 0 4px" }}>
                Sou Guia
              </p>
              <p style={{ fontSize: "13px", color: "var(--stone-500)", margin: 0 }}>
                Cadastre-se como condutor em uma operadora parceira
              </p>
            </button>
          </div>

          <p
            style={{
              fontSize: "14px",
              color: "var(--stone-500)",
              textAlign: "center",
              marginTop: "28px",
            }}
          >
            Já tem conta?{" "}
            <Link href="/login" style={{ color: "var(--ochre)", fontWeight: 600, textDecoration: "none" }}>
              Entrar
            </Link>
          </p>
        </div>
      </main>
    )
  }

  // ── Step: guide ───────────────────────────────────────────────────────────
  if (step === "guide") {
    return (
      <main
        style={{
          minHeight: "100dvh",
          background: "var(--stone-50)",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          padding: "24px",
        }}
      >
        <div
          style={{
            background: "white",
            border: "1px solid var(--stone-200)",
            borderRadius: "8px",
            padding: "clamp(32px, 5vw, 48px) clamp(24px, 5vw, 40px)",
            width: "100%",
            maxWidth: "480px",
          }}
        >
          <button
            onClick={() => { setStep("choose"); setGuideSlug(""); setGuideSlugError(null) }}
            style={{
              background: "none",
              border: "none",
              cursor: "pointer",
              fontSize: "13px",
              fontWeight: 600,
              color: "var(--stone-500)",
              padding: 0,
              marginBottom: "24px",
              display: "block",
            }}
          >
            ← Voltar
          </button>

          <p
            style={{
              fontSize: "11px",
              fontWeight: 600,
              letterSpacing: "0.06em",
              textTransform: "uppercase",
              color: "var(--ochre)",
              marginBottom: "8px",
            }}
          >
            CAPI
          </p>
          <h1
            style={{
              fontFamily: "var(--font-display)",
              fontSize: "24px",
              fontWeight: 400,
              color: "var(--stone-900)",
              marginBottom: "8px",
            }}
          >
            Cadastro de Guia
          </h1>
          <p style={{ fontSize: "14px", color: "var(--stone-500)", marginBottom: "32px" }}>
            Informe o código da operadora à qual você pertence.
            Peça esse código ao admin da sua operadora.
          </p>

          {guideSlugError && (
            <div
              role="alert"
              aria-live="polite"
              style={{
                background: "#FEF2F2",
                border: "1px solid #FCA5A5",
                borderRadius: "4px",
                padding: "8px 12px",
                marginBottom: "16px",
                fontSize: "14px",
                color: "#DC2626",
              }}
            >
              {guideSlugError}
            </div>
          )}

          <form onSubmit={handleGuideSubmit} noValidate>
            <div style={{ marginBottom: "24px" }}>
              <label
                htmlFor="guide-slug"
                style={{ display: "block", fontSize: "14px", fontWeight: 500, color: "var(--stone-700)", marginBottom: "6px" }}
              >
                Código da operadora
              </label>
              <input
                id="guide-slug"
                type="text"
                required
                placeholder="ex: trilhas-do-norte"
                value={guideSlug}
                onChange={(e) => setGuideSlug(e.target.value.toLowerCase().replace(/\s/g, "-"))}
                style={{
                  width: "100%",
                  padding: "10px 12px",
                  border: "1px solid var(--stone-200)",
                  borderRadius: "4px",
                  fontSize: "16px",
                  fontFamily: "var(--font-body)",
                  boxSizing: "border-box",
                }}
              />
            </div>

            <button
              type="submit"
              disabled={guideSlugChecking}
              style={{
                width: "100%",
                minHeight: "44px",
                background: guideSlugChecking ? "var(--stone-400)" : "var(--ochre)",
                color: "white",
                border: "none",
                borderRadius: "4px",
                fontSize: "16px",
                fontWeight: 600,
                cursor: guideSlugChecking ? "not-allowed" : "pointer",
                fontFamily: "var(--font-body)",
              }}
            >
              {guideSlugChecking ? "Verificando…" : "Continuar"}
            </button>
          </form>
        </div>
      </main>
    )
  }

  // ── Step: operator ────────────────────────────────────────────────────────
  return (
    <main
      style={{
        minHeight: "100dvh",
        background: "var(--stone-50)",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        padding: "24px",
      }}
    >
      <div
        style={{
          background: "white",
          border: "1px solid var(--stone-200)",
          borderRadius: "8px",
          padding: "clamp(32px, 5vw, 48px) clamp(24px, 5vw, 40px)",
          width: "100%",
          maxWidth: "480px",
        }}
      >
        <button
          onClick={() => { setStep("choose"); setError(null) }}
          style={{
            background: "none",
            border: "none",
            cursor: "pointer",
            fontSize: "13px",
            fontWeight: 600,
            color: "var(--stone-500)",
            padding: 0,
            marginBottom: "24px",
            display: "block",
          }}
        >
          ← Voltar
        </button>

        <p
          style={{
            fontSize: "11px",
            fontWeight: 600,
            letterSpacing: "0.06em",
            textTransform: "uppercase",
            color: "var(--ochre)",
            marginBottom: "8px",
          }}
        >
          CAPI
        </p>
        <h1
          style={{
            fontFamily: "var(--font-display)",
            fontSize: "24px",
            fontWeight: 400,
            color: "var(--stone-900)",
            marginBottom: "32px",
          }}
        >
          Cadastre sua Operadora
        </h1>

        {error && (
          <div
            role="alert"
            aria-live="polite"
            style={{
              background: "#FEF2F2",
              border: "1px solid #FCA5A5",
              borderRadius: "4px",
              padding: "8px 12px",
              marginBottom: "16px",
              fontSize: "14px",
              color: "#DC2626",
            }}
          >
            {error}
          </div>
        )}

        <form onSubmit={handleOperatorSubmit} noValidate>
          <div style={{ marginBottom: "20px" }}>
            <label
              htmlFor="name"
              style={{ display: "block", fontSize: "14px", fontWeight: 500, color: "var(--stone-700)", marginBottom: "6px" }}
            >
              Nome fantasia da operadora
            </label>
            <input
              id="name"
              type="text"
              required
              value={name}
              onChange={(e) => { setName(e.target.value); slugAutoGenerated.current = true }}
              style={{
                width: "100%",
                padding: "10px 12px",
                border: "1px solid var(--stone-200)",
                borderRadius: "4px",
                fontSize: "16px",
                fontFamily: "var(--font-body)",
                boxSizing: "border-box",
              }}
            />
          </div>

          <div style={{ marginBottom: "20px" }}>
            <label
              htmlFor="slug"
              style={{ display: "block", fontSize: "14px", fontWeight: 500, color: "var(--stone-700)", marginBottom: "6px" }}
            >
              Slug da operadora
            </label>
            <input
              id="slug"
              type="text"
              required
              value={slug}
              onChange={(e) => handleSlugChange(e.target.value)}
              style={{
                width: "100%",
                padding: "10px 12px",
                border: "1px solid var(--stone-200)",
                borderRadius: "4px",
                fontSize: "16px",
                fontFamily: "var(--font-body)",
                boxSizing: "border-box",
              }}
            />
            <div style={{ marginTop: "4px", minHeight: "20px" }}>{slugIndicator}</div>
          </div>

          <div style={{ marginBottom: "20px" }}>
            <label
              htmlFor="email"
              style={{ display: "block", fontSize: "14px", fontWeight: 500, color: "var(--stone-700)", marginBottom: "6px" }}
            >
              Email
            </label>
            <input
              id="email"
              type="email"
              required
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              style={{
                width: "100%",
                padding: "10px 12px",
                border: "1px solid var(--stone-200)",
                borderRadius: "4px",
                fontSize: "16px",
                fontFamily: "var(--font-body)",
                boxSizing: "border-box",
              }}
            />
          </div>

          <div style={{ marginBottom: "20px" }}>
            <label
              htmlFor="cnpj"
              style={{ display: "block", fontSize: "14px", fontWeight: 500, color: "var(--stone-700)", marginBottom: "6px" }}
            >
              CNPJ
            </label>
            <input
              id="cnpj"
              type="text"
              required
              placeholder="XX.XXX.XXX/XXXX-XX"
              minLength={14}
              maxLength={18}
              value={cnpj}
              onChange={(e) => setCnpj(e.target.value)}
              style={{
                width: "100%",
                padding: "10px 12px",
                border: "1px solid var(--stone-200)",
                borderRadius: "4px",
                fontSize: "16px",
                fontFamily: "var(--font-body)",
                boxSizing: "border-box",
              }}
            />
          </div>

          <div style={{ marginBottom: "28px" }}>
            <label
              htmlFor="password"
              style={{ display: "block", fontSize: "14px", fontWeight: 500, color: "var(--stone-700)", marginBottom: "6px" }}
            >
              Senha
            </label>
            <input
              id="password"
              type="password"
              required
              minLength={8}
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              style={{
                width: "100%",
                padding: "10px 12px",
                border: "1px solid var(--stone-200)",
                borderRadius: "4px",
                fontSize: "16px",
                fontFamily: "var(--font-body)",
                boxSizing: "border-box",
              }}
            />
          </div>

          <button
            type="submit"
            disabled={loading}
            style={{
              width: "100%",
              minHeight: "44px",
              background: loading ? "var(--stone-400)" : "var(--ochre)",
              color: "white",
              border: "none",
              borderRadius: "4px",
              fontSize: "16px",
              fontWeight: 600,
              cursor: loading ? "not-allowed" : "pointer",
              fontFamily: "var(--font-body)",
            }}
          >
            {loading ? "Cadastrando…" : "Cadastrar Operadora"}
          </button>
        </form>

        <p
          style={{
            fontSize: "14px",
            color: "var(--stone-500)",
            textAlign: "center",
            marginTop: "24px",
          }}
        >
          Já tem conta?{" "}
          <Link href="/login" style={{ color: "var(--ochre)", fontWeight: 600, textDecoration: "none" }}>
            Acesse o painel da sua operadora.
          </Link>
        </p>
      </div>
    </main>
  )
}
