"use client"
import { useState, useEffect, useRef, type ReactNode } from "react"
import { useRouter } from "next/navigation"
import Image from "next/image"
import Link from "next/link"
import { ArrowLeft, Building2, CalendarCheck, Check, Compass, ShieldCheck, UserRound } from "lucide-react"
import { Alert, Button, Input, ListGroup, ListRow, Stepper } from "@/src/components/ui/capi"

/* ── Layout de acesso (local; candidato a componente do DS) ── */
const BENEFITS = [
  { icon: Compass, text: "Roteiros e guias locais num só lugar" },
  { icon: CalendarCheck, text: "Reservas, agenda e check-in organizados" },
  { icon: ShieldCheck, text: "Guias e operadoras aprovados pela equipe CAPI" },
]

function AuthLayout({ children }: { children: ReactNode }) {
  return (
    <div className="grid min-h-dvh bg-page lg:grid-cols-[minmax(0,5fr)_minmax(0,6fr)]">
      <aside className="sticky top-0 hidden h-dvh flex-col justify-between gap-12 bg-surface-brand p-12 text-on-brand lg:flex">
        <Link href="/" className="inline-block self-start rounded-sm">
          <Image src="/images/logo.png" alt="CAPI" width={120} height={108} className="block brightness-0 invert" />
        </Link>
        <div>
          <p className="font-display text-4xl leading-tight xl:text-5xl">Caminho entre quem explora e quem opera</p>
          <ul className="mt-10 flex flex-col gap-5">
            {BENEFITS.map(({ icon: Icon, text }) => (
              <li key={text} className="flex items-center gap-3" style={{ color: "var(--text-on-brand-secondary)" }}>
                <span className="flex size-10 shrink-0 items-center justify-center rounded-full text-on-brand" style={{ background: "var(--terra-700)" }}>
                  <Icon size={20} strokeWidth={1.75} aria-hidden="true" />
                </span>
                {text}
              </li>
            ))}
          </ul>
        </div>
      </aside>
      <main className="flex min-w-0 items-center justify-center py-10 lg:py-16">
        <div className="capi-container capi-container--form">
          <Link href="/" className="mb-8 inline-block rounded-sm lg:hidden">
            <Image src="/images/logo.png" alt="CAPI" width={120} height={108} priority className="block in-data-[theme=dark]:brightness-0 in-data-[theme=dark]:invert" />
          </Link>
          {children}
        </div>
      </main>
    </div>
  )
}

function FormSection({ title, children }: { title: string; children: ReactNode }) {
  return (
    <fieldset className="flex min-w-0 flex-col gap-5 border-0">
      <legend className="mb-4 text-base font-bold">{title}</legend>
      {children}
    </fieldset>
  )
}

function slugify(str: string): string {
  return str
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
}

type Step = "choose" | "operator" | "guide"
type SlugStatus = "idle" | "checking" | "available" | "unavailable" | "invalid-format"

export default function OnboardingPage() {
  const router = useRouter()
  const [step, setStep] = useState<Step>("choose")

  // Operator form state
  const [name, setName] = useState("")
  const [slug, setSlug] = useState("")
  const [email, setEmail] = useState("")
  const [cnpj, setCnpj] = useState("")
  const [password, setPassword] = useState("")
  const [slugStatus, setSlugStatus] = useState<SlugStatus>("idle")
  const slugAutoGenerated = useRef(true)

  // Guide lookup state
  const [guideSlug, setGuideSlug] = useState("")
  const [guideSlugChecking, setGuideSlugChecking] = useState(false)
  const [guideSlugError, setGuideSlugError] = useState<string | null>(null)

  const [error, setError] = useState<string | null>(null)
  const [loading, setLoading] = useState(false)

  // Auto-populate slug from operator name
  useEffect(() => {
    if (slugAutoGenerated.current && name) {
      setSlug(slugify(name))
      setSlugStatus("idle")
    }
  }, [name])

  // Debounced operator slug availability check
  useEffect(() => {
    if (step !== "operator") return
    if (!slug) { setSlugStatus("idle"); return }
    if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug)) { setSlugStatus("invalid-format"); return }
    setSlugStatus("checking")
    const timer = setTimeout(async () => {
      try {
        const res = await fetch(`/api/tenants/check-slug?slug=${encodeURIComponent(slug)}`)
        if (res.ok) {
          const data = await res.json()
          setSlugStatus(data.available ? "available" : "unavailable")
        } else {
          setSlugStatus("idle")
        }
      } catch {
        setSlugStatus("idle")
      }
    }, 500)
    return () => clearTimeout(timer)
  }, [slug, step])

  function handleSlugChange(value: string) {
    slugAutoGenerated.current = false
    setSlug(value)
  }

  async function handleOperatorSubmit(e: React.FormEvent) {
    e.preventDefault()
    if (slugStatus === "unavailable" || slugStatus === "invalid-format" || slugStatus === "checking") {
      setError("Corrija o slug antes de enviar.")
      return
    }
    setError(null)
    setLoading(true)
    try {
      const res = await fetch(`/api/tenants/signup`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ name, slug, email, password, cnpj }),
      })
      if (res.ok) {
        router.push("/onboarding/aguardando")
      } else {
        const data = await res.json()
        setError(data.message ?? "Erro ao cadastrar operadora. Tente novamente.")
      }
    } catch {
      setError("Erro de conexão. Verifique sua internet e tente novamente.")
    } finally {
      setLoading(false)
    }
  }

  async function handleGuideSubmit(e: React.FormEvent) {
    e.preventDefault()
    setGuideSlugError(null)
    const normalized = guideSlug.trim().toLowerCase()
    if (!normalized) { setGuideSlugError("Informe o código da operadora."); return }
    setGuideSlugChecking(true)
    try {
      const res = await fetch(`/api/tenants/check-slug?slug=${encodeURIComponent(normalized)}`)
      if (res.ok) {
        const data = await res.json()
        // available: true → slug is FREE (tenant does NOT exist)
        if (data.available) {
          setGuideSlugError("Operadora não encontrada. Verifique o código e tente novamente.")
        } else {
          router.push(`/${normalized}/cadastro`)
        }
      } else {
        setGuideSlugError("Erro ao verificar operadora. Tente novamente.")
      }
    } catch {
      setGuideSlugError("Erro de conexão. Verifique sua internet e tente novamente.")
    } finally {
      setGuideSlugChecking(false)
    }
  }

  // Status do slug vira dica/erro do campo (só apresentação; a verificação é a mesma).
  const slugError =
    slugStatus === "unavailable"
      ? "Esse código já está em uso. Escolha outro."
      : slugStatus === "invalid-format"
        ? "Formato inválido: use letras minúsculas, números e hífens."
        : null
  const slugHint =
    slugStatus === "available" ? (
      <span className="inline-flex items-center gap-1 text-success" aria-live="polite">
        <Check size={16} strokeWidth={1.75} aria-hidden="true" /> Disponível
      </span>
    ) : slugStatus === "checking" ? (
      <span aria-live="polite">Verificando disponibilidade…</span>
    ) : (
      "Use letras minúsculas, números e hífens. Os guias usam esse código para se cadastrar."
    )

  // Código não encontrado/vazio vai para o campo; falhas de rede ficam no Alert.
  const guideSlugFieldError = guideSlugError && !guideSlugError.startsWith("Erro") ? guideSlugError : null
  const guideSlugAlert = guideSlugError && !guideSlugFieldError ? guideSlugError : null

  // ── Step: choose ──────────────────────────────────────────────────────────
  if (step === "choose") {
    return (
      <AuthLayout>
        <Stepper steps={["Tipo de conta", "Seus dados", "Aprovação"]} current={0} />
        <h1 className="mt-8 text-2xl font-bold">Criar conta</h1>
        <p className="mt-2 text-fg-secondary">Como você quer usar o CAPI?</p>

        <div className="mt-8">
          <ListGroup>
            <ListRow
              onClick={() => setStep("operator")}
              leading={
                <span className="flex size-10 items-center justify-center rounded-full bg-subtle text-fg-primary">
                  <Building2 size={20} strokeWidth={1.75} aria-hidden="true" />
                </span>
              }
              title="Sou operadora"
              subtitle="Cadastre sua empresa e gerencie guias e roteiros"
            />
            <ListRow
              onClick={() => setStep("guide")}
              leading={
                <span className="flex size-10 items-center justify-center rounded-full bg-subtle text-fg-primary">
                  <UserRound size={20} strokeWidth={1.75} aria-hidden="true" />
                </span>
              }
              title="Sou guia"
              subtitle="Cadastre-se como condutor em uma operadora parceira"
            />
          </ListGroup>
        </div>

        <p className="mt-6 text-center text-sm text-fg-secondary">
          Já tem conta?{" "}
          <Link href="/login" className="inline-flex min-h-11 items-center font-semibold text-fg-primary underline-offset-4 hover:underline">
            Entrar
          </Link>
        </p>
      </AuthLayout>
    )
  }

  // ── Step: guide ───────────────────────────────────────────────────────────
  if (step === "guide") {
    return (
      <AuthLayout>
        <Button
          variant="ghost"
          size="sm"
          iconLeft={ArrowLeft}
          className="mb-4 -ml-2"
          onClick={() => { setStep("choose"); setGuideSlug(""); setGuideSlugError(null) }}
        >
          Voltar
        </Button>
        <Stepper steps={["Tipo de conta", "Operadora", "Seus dados"]} current={1} />
        <h1 className="mt-8 text-2xl font-bold">Cadastro de guia</h1>
        <p className="mt-2 text-fg-secondary">
          Informe o código da operadora à qual você pertence.
          Peça esse código ao admin da sua operadora.
        </p>

        <form onSubmit={handleGuideSubmit} noValidate className="mt-8 flex flex-col gap-5">
          <Input
            id="guide-slug"
            label="Código da operadora"
            type="text"
            required
            autoComplete="off"
            autoCapitalize="none"
            spellCheck={false}
            placeholder="ex: trilhas-do-norte"
            value={guideSlug}
            onChange={(e) => setGuideSlug(e.target.value.toLowerCase().replace(/\s/g, "-"))}
            error={guideSlugFieldError}
          />

          {guideSlugAlert && <Alert tone="danger">{guideSlugAlert}</Alert>}

          <Button type="submit" size="lg" fullWidth loading={guideSlugChecking}>
            Continuar
          </Button>
        </form>

        <p className="mt-6 text-center text-sm text-fg-secondary">
          Sem código de operadora?{" "}
          <Link href="/cadastro/guia" className="inline-flex min-h-11 items-center font-semibold text-fg-primary underline-offset-4 hover:underline">
            Cadastre-se como guia independente
          </Link>
        </p>
      </AuthLayout>
    )
  }

  // ── Step: operator ────────────────────────────────────────────────────────
  return (
    <AuthLayout>
      <Button
        variant="ghost"
        size="sm"
        iconLeft={ArrowLeft}
        className="mb-4 -ml-2"
        onClick={() => { setStep("choose"); setError(null) }}
      >
        Voltar
      </Button>
      <Stepper steps={["Tipo de conta", "Dados da operadora", "Aprovação"]} current={1} />
      <h1 className="mt-8 text-2xl font-bold">Cadastre sua operadora</h1>
      <p className="mt-2 text-fg-secondary">Depois do envio, a equipe CAPI analisa e libera o acesso ao painel.</p>

      <form onSubmit={handleOperatorSubmit} noValidate className="mt-8 flex flex-col gap-8">
        <FormSection title="Sua operadora">
          <Input
            id="name"
            label="Nome fantasia da operadora"
            type="text"
            required
            autoComplete="organization"
            value={name}
            onChange={(e) => { setName(e.target.value); slugAutoGenerated.current = true }}
          />
          <Input
            id="slug"
            label="Código da operadora (slug)"
            type="text"
            required
            autoComplete="off"
            autoCapitalize="none"
            spellCheck={false}
            value={slug}
            onChange={(e) => handleSlugChange(e.target.value)}
            error={slugError}
            hint={slugHint}
          />
          <Input
            id="cnpj"
            label="CNPJ"
            type="text"
            inputMode="numeric"
            autoComplete="off"
            required
            placeholder="XX.XXX.XXX/XXXX-XX"
            minLength={14}
            maxLength={18}
            value={cnpj}
            onChange={(e) => setCnpj(e.target.value)}
          />
        </FormSection>

        <FormSection title="Acesso ao painel">
          <Input
            id="email"
            label="E-mail"
            type="email"
            inputMode="email"
            required
            autoComplete="email"
            autoCapitalize="none"
            spellCheck={false}
            value={email}
            onChange={(e) => setEmail(e.target.value)}
          />
          <Input
            id="password"
            label="Senha"
            type="password"
            required
            minLength={8}
            autoComplete="new-password"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            hint="Mínimo 8 caracteres"
          />
        </FormSection>

        <div className="flex flex-col gap-4">
          {error && <Alert tone="danger">{error}</Alert>}
          <Button type="submit" size="lg" fullWidth loading={loading}>
            Cadastrar operadora
          </Button>
        </div>
      </form>

      <p className="mt-6 text-center text-sm text-fg-secondary">
        Já tem conta?{" "}
        <Link href="/login" className="inline-flex min-h-11 items-center font-semibold text-fg-primary underline-offset-4 hover:underline">
          Acesse o painel da sua operadora
        </Link>
      </p>
    </AuthLayout>
  )
}
