"use client"
import { useState, useEffect, useRef } from "react"
import { useRouter } from "next/navigation"

const API_URL = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:3333"

function slugify(str: string): string {
  return str
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
}

type SlugStatus = "idle" | "checking" | "available" | "unavailable" | "invalid-format"

export default function OnboardingPage() {
  const router = useRouter()

  const [name, setName] = useState("")
  const [slug, setSlug] = useState("")
  const [email, setEmail] = useState("")
  const [password, setPassword] = useState("")
  const [error, setError] = useState<string | null>(null)
  const [loading, setLoading] = useState(false)

  const [slugStatus, setSlugStatus] = useState<SlugStatus>("idle")
  const slugAutoGenerated = useRef(true)

  // Auto-populate slug from name when not manually edited
  useEffect(() => {
    if (slugAutoGenerated.current && name) {
      setSlug(slugify(name))
      setSlugStatus("idle")
    }
  }, [name])

  // Debounced slug availability check (500ms)
  useEffect(() => {
    if (!slug) {
      setSlugStatus("idle")
      return
    }
    // Basic format validation
    if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug)) {
      setSlugStatus("invalid-format")
      return
    }
    setSlugStatus("checking")
    const timer = setTimeout(async () => {
      try {
        const res = await fetch(`${API_URL}/tenants/check-slug?slug=${encodeURIComponent(slug)}`)
        if (res.ok) {
          const data = await res.json()
          setSlugStatus(data.available ? "available" : "unavailable")
        } else {
          setSlugStatus("idle")
        }
      } catch {
        setSlugStatus("idle")
      }
    }, 500)
    return () => clearTimeout(timer)
  }, [slug])

  function handleSlugChange(value: string) {
    slugAutoGenerated.current = false
    setSlug(value)
  }

  function handleNameChange(value: string) {
    setName(value)
    if (slugAutoGenerated.current) {
      // keep auto-generation active
    }
  }

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault()
    setError(null)
    setLoading(true)
    try {
      const res = await fetch(`${API_URL}/tenants/signup`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ name, slug, email, password }),
      })
      if (res.ok) {
        router.push("/onboarding/aguardando")
      } else {
        const data = await res.json()
        setError(data.message ?? "Erro ao cadastrar operadora. Tente novamente.")
      }
    } catch {
      setError("Erro de conexão. Verifique sua internet e tente novamente.")
    } finally {
      setLoading(false)
    }
  }

  const slugIndicator =
    slugStatus === "available" ? (
      <span style={{ color: "#15803D", fontSize: "14px" }} aria-live="polite">✓ Disponível</span>
    ) : slugStatus === "unavailable" ? (
      <span style={{ color: "#DC2626", fontSize: "14px" }} aria-live="polite">✗ Já utilizado</span>
    ) : slugStatus === "checking" ? (
      <span style={{ color: "var(--stone-500)", fontSize: "14px" }} aria-live="polite">Verificando…</span>
    ) : slugStatus === "invalid-format" ? (
      <span style={{ color: "#DC2626", fontSize: "14px" }} aria-live="polite">✗ Formato inválido (use letras, números e hífens)</span>
    ) : null

  return (
    <main
      style={{
        minHeight: "100dvh",
        background: "var(--stone-50)",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        padding: "24px",
      }}
    >
      <div
        style={{
          background: "white",
          border: "1px solid var(--stone-200)",
          borderRadius: "8px",
          padding: "clamp(32px, 5vw, 48px) clamp(24px, 5vw, 40px)",
          width: "100%",
          maxWidth: "480px",
        }}
      >
        <p
          style={{
            fontSize: "11px",
            fontWeight: 600,
            letterSpacing: "0.06em",
            textTransform: "uppercase",
            color: "var(--ochre)",
            marginBottom: "8px",
          }}
        >
          CAPI
        </p>
        <h1
          style={{
            fontFamily: "var(--font-display)",
            fontSize: "24px",
            fontWeight: 400,
            color: "var(--stone-900)",
            marginBottom: "32px",
          }}
        >
          Cadastre sua Operadora
        </h1>

        {error && (
          <div
            role="alert"
            aria-live="polite"
            style={{
              background: "#FEF2F2",
              border: "1px solid #FCA5A5",
              borderRadius: "4px",
              padding: "8px 12px",
              marginBottom: "16px",
              fontSize: "14px",
              color: "#DC2626",
            }}
          >
            {error}
          </div>
        )}

        <form onSubmit={handleSubmit} noValidate>
          {/* Nome da operadora */}
          <div style={{ marginBottom: "20px" }}>
            <label
              htmlFor="name"
              style={{ display: "block", fontSize: "14px", fontWeight: 500, color: "var(--stone-700)", marginBottom: "6px" }}
            >
              Nome fantasia da operadora
            </label>
            <input
              id="name"
              type="text"
              required
              value={name}
              onChange={(e) => handleNameChange(e.target.value)}
              style={{
                width: "100%",
                padding: "10px 12px",
                border: "1px solid var(--stone-200)",
                borderRadius: "4px",
                fontSize: "16px",
                fontFamily: "var(--font-body)",
                boxSizing: "border-box",
              }}
            />
          </div>

          {/* Slug */}
          <div style={{ marginBottom: "20px" }}>
            <label
              htmlFor="slug"
              style={{ display: "block", fontSize: "14px", fontWeight: 500, color: "var(--stone-700)", marginBottom: "6px" }}
            >
              Slug da operadora
            </label>
            <input
              id="slug"
              type="text"
              required
              value={slug}
              onChange={(e) => handleSlugChange(e.target.value)}
              style={{
                width: "100%",
                padding: "10px 12px",
                border: "1px solid var(--stone-200)",
                borderRadius: "4px",
                fontSize: "16px",
                fontFamily: "var(--font-body)",
                boxSizing: "border-box",
              }}
            />
            <div style={{ marginTop: "4px", minHeight: "20px" }}>
              {slugIndicator}
            </div>
          </div>

          {/* Email */}
          <div style={{ marginBottom: "20px" }}>
            <label
              htmlFor="email"
              style={{ display: "block", fontSize: "14px", fontWeight: 500, color: "var(--stone-700)", marginBottom: "6px" }}
            >
              Email
            </label>
            <input
              id="email"
              type="email"
              required
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              style={{
                width: "100%",
                padding: "10px 12px",
                border: "1px solid var(--stone-200)",
                borderRadius: "4px",
                fontSize: "16px",
                fontFamily: "var(--font-body)",
                boxSizing: "border-box",
              }}
            />
          </div>

          {/* Senha */}
          <div style={{ marginBottom: "28px" }}>
            <label
              htmlFor="password"
              style={{ display: "block", fontSize: "14px", fontWeight: 500, color: "var(--stone-700)", marginBottom: "6px" }}
            >
              Senha
            </label>
            <input
              id="password"
              type="password"
              required
              minLength={8}
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              style={{
                width: "100%",
                padding: "10px 12px",
                border: "1px solid var(--stone-200)",
                borderRadius: "4px",
                fontSize: "16px",
                fontFamily: "var(--font-body)",
                boxSizing: "border-box",
              }}
            />
          </div>

          <button
            type="submit"
            disabled={loading}
            style={{
              width: "100%",
              minHeight: "44px",
              background: loading ? "var(--stone-400)" : "var(--ochre)",
              color: "white",
              border: "none",
              borderRadius: "4px",
              fontSize: "16px",
              fontWeight: 600,
              cursor: loading ? "not-allowed" : "pointer",
              fontFamily: "var(--font-body)",
            }}
          >
            {loading ? "Cadastrando…" : "Cadastrar Operadora"}
          </button>
        </form>

        <p
          style={{
            fontSize: "14px",
            color: "var(--stone-500)",
            textAlign: "center",
            marginTop: "24px",
          }}
        >
          Já tem conta?{" "}
          <span style={{ color: "var(--ochre)", cursor: "pointer" }}>
            Acesse o painel da sua operadora.
          </span>
        </p>
      </div>
    </main>
  )
}
